Pedantic and Picking
grace125/bevy_midi pull request #2
Opened 2022-08-16 01:00 UTC by BlackPhlox

2022-08-23 11:09 UTC, BlackPhlox commented
@grace125 I fixed some pedantic errors and tried to do a POC on clicking to play the piano, I got something but it still needs some work. Also, I sprained my wrist and had other personal stuff, so I haven't been able to do much work since the latest commit. I can pick this up at the end of the week. However, any feedback is much appreciated.

2022-08-31 05:10 UTC, grace125 requested changes
Some minor changes.

2022-08-31 05:10 UTC, grace125 commented on src/input.rs
> +            .expect("RefreshPorts");
These `expect` error messages should probably be of the form "couldn't refresh input ports: channel closed" to more accurately describe what went wrong. Same thing in `MidiOutput`'s methods.

2022-08-31 05:10 UTC, grace125 commented on src/input.rs
> +                        .expect("Send Message");
Now that I think about it, we don't want this to panic at all. If a `SendError<Reply>` occurs here, then the `Reply` channel is closed. This can only happen if the `MidiInput` resource has been dropped, and if this is the case then the `Message` channel will also be closed. Thus, a `ReceiveError<Message>` would eventually terminate the outer `while let` loop and the thread could close without panicking.

So instead, we'd want `let _ = s.send(Reply::Midi(MidiData { ...` instead of using `expect`.

2022-08-31 05:10 UTC, grace125 commented on src/input.rs
> +                            .expect("Send message");
This too should be `let _ = s.send(Reply::Midi(MidiData {...` instead of `expect`.

2022-08-31 05:29 UTC, grace125 commented
@BlackPhlox I've been a bit busy myself, but I'm free the next couple of days to finish off what we've been working on.

2022-08-31 18:54 UTC, BlackPhlox commented on src/input.rs
> +            .expect("RefreshPorts");
`thread 'main' panicked at 'couldn't refresh input ports: channel closed: "sending on a disconnected channel"',...`
I remove _channel closed_ for brevity as the inner error indicates the same thing:
`thread 'main' panicked at 'Couldn't refresh input ports: "sending on a disconnected channel"',...`

2022-08-31 19:45 UTC, grace125 commented on src/input.rs
> +            .expect("RefreshPorts");
Okay that makes sense

2022-08-31 19:48 UTC, grace125 commented on src/output.rs
> +            .expect("RefreshPorts");
These `expect` error messages should also be changed

2022-08-31 21:58 UTC, grace125 requested changes

2022-08-31 21:58 UTC, grace125 commented on src/input.rs
> -        self.sender.send(Message::RefreshPorts).unwrap();
I don't really see a reason for these messages to be constants. I'd argue that there's not much gained from the deduplication across `MidiInput`/`MidiOutput`, and it makes our code less readable to put the panic message elsewhere.

2022-08-31 21:58 UTC, grace125 commented on src/output.rs
> +        self.sender.send(Message::Midi(msg)).expect("Send MIDI");
Forgot to update this error message. Probably should be "Couldn't send MIDI message".

2022-08-31 21:58 UTC, grace125 commented on src/lib.rs
> +const REFRESH_PORTS_ERROR_MSG: &str = "Couldn't refresh input ports";
In `MidiOutput`'s `refresh_ports` method, it'd be _output ports_ and not _input ports_.

2022-08-31 22:30 UTC, merged